### ISSUE TITLE
.NET 5 Blazor Server ServiceStack template

### ISSUE THREAD

**Issue by adrianwright109** [nukedbit/blazor-wasm-servicestack#2]
I'm looking to build a .NET 5.0 Blazor Server app from scratch. Rather than using the standard `blazorserver` template out of the box I would like to base the app on a ServiceStack API backend.

I see from the ServiceStack [templates-blazor](https://docs.servicestack.net/templates-blazor) docs that the ServiceStack community has created this [.NET 5.0 Blazor WASM Template](https://github.com/nukedbit/blazor-wasm-servicestack).

I was wondering if there were any plans to create a similar template but for .NET 5.0 Blazor Server ?

Or alternatively how easy would it be to convert this [.NET 5.0 Blazor WASM Template](https://github.com/nukedbit/blazor-wasm-servicestack) for Blazor Server ?

**Comment by nukedbit** [comment]
Hi @adrianwright109  i have made an older template for blazor server I think it shouldn't be to much an effort to update it. Beware that blazor server side behave in a different manner, and to integrate ServiceStack the only way I have found is to use jsonserviceclient server side. That is because blazor use a signalr connection to render pages to we don't have a HTTP context that is needed to call servicestack services.
[Blazor Server Side Template](https://github.com/nukedbit/blazor-servicestack) if you take a look at the code integrations points is https://github.com/nukedbit/blazor-servicestack/blob/master/MyApp/AuthenticationStateExtensions.cs providing an extension to create a serviceclient, also I made use of API keys for authenticate the request. 
https://github.com/nukedbit/blazor-servicestack/blob/772f308e8ff6bed872fc5cc6833fe32820bcfaab/MyApp/Configure.Auth.cs#L52
